version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:${DOCKER_PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks: 
      - blog-api

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_DOCKER_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - blog-api

volumes:
  postgres_data:

networks:
  blog-api: {}
