name: Deploy to Railway

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Login to Railway
        run: railway login
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Run unit and e2e test cases
        run: npm run test

      - name: Deploy to Railway
        run: railway up --service app
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
