name: Deploy to Railway

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # Skip the login and directly link the Railway project
      - name: Link Railway Project
        run: railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}

      # Deploy to Railway
      - name: Deploy to Railway
        run: railway up
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
